### PR TITLE
Fix issues found by peilun.

### PR DESCRIPTION
**Pull request by yangzhe1990**
This change is [Reviewable](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2)

### CODE REVIEW

**Review by peilun-conflux — APPROVED** [review]
> Reviewed 12 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2)* status: all files reviewed, 3 unresolved discussions (waiting on @yangzhe1990)

___
*[core/src/storage/impls/merkle_patricia_trie/compressed_path.rs, line 233 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveR8d64ebocHrgxeKc:-LveR8d64ebocHrgxeKd:bo8w686) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/merkle_patricia_trie/compressed_path.rs#L233)):*
> ```
> x 
> ```
end with
___
*[core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs, line 950 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveUSuGDC2MGq8wxmR6:-LveUSuGDC2MGq8wxmR7:bvbxfh5) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs#L950)):*
> ```
> 
>                         child_node.mpt = self.take_mpt();
>                         self.mpt = child_node.write_out()?;
> ```
Move out of if-else/
___
*[core/src/storage/impls/snapshot_sync/offer/mpt_slicer.rs, line 83 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveW5-eCgxiohkdtyfb:-LveW5-eCgxiohkdtyfc:b-6a3sic) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/snapshot_sync/offer/mpt_slicer.rs#L83)):*
> ```
>                 // FIXME: try if we can do it.
> ```
remove.

**Review by peilun-conflux — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2)* status: all files reviewed, 5 unresolved discussions (waiting on @yangzhe1990)

___
*[core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs, line 402 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveY22j569rhkg7p1-a:-LveY22j569rhkg7p1-b:b-1urwcl) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs#L402)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 
>                 last_node.get_read_write_path_node().path_db_key =
>                     CompressedPathRaw::extend_path(
>                         &fork_node.get_basic_path_node().full_path_to_node,
>                         unmatched_child_index,
> 
>                     );
> ```
</details>

Remove last_node from db in `in_place` mode.
___
*[core/src/storage/impls/storage_db/sqlite.rs, line 195 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveXK8p7wq_GRtcNc1b:-LveXK8q5MwctOHvcv0q:b-5260qx) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/storage_db/sqlite.rs#L195)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 
>         for path in Self::possible_temporary_files(db_path) {
>             match fs::remove_file(path) {
>                 Ok(_) => {
>                     removed = true;
>                 }
> ```
</details>

Double check.

**Review by yangzhe1990 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @peilun-conflux and @yangzhe1990)

___
*[core/src/storage/impls/merkle_patricia_trie/compressed_path.rs, line 233 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveR8d64ebocHrgxeKc:-LveZKxCA7F4XBKsRnCb:b-896fix) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/merkle_patricia_trie/compressed_path.rs#L233)):*
<details><summary><i>Previously, peilun-conflux wrote…</i></summary><blockquote>

> ```
> x 
> ```
end with
</blockquote></details>

Done.
___
*[core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs, line 402 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveY22j569rhkg7p1-a:-Lvf0OS33y7lJnxsYHC5:b-896fix) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs#L402)):*
<details><summary><i>Previously, peilun-conflux wrote…</i></summary><blockquote>

> ```
> 
>                 last_node.get_read_write_path_node().path_db_key =
>                     CompressedPathRaw::extend_path(
>                         &fork_node.get_basic_path_node().full_path_to_node,
>                         unmatched_child_index,
> 
>                     );
> ```
Remove last_node from db in `in_place` mode.
</blockquote></details>

Done.
___
*[core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs, line 950 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveUSuGDC2MGq8wxmR6:-LveaH83DCAcO1EPp0uc:b-896fix) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/merkle_patricia_trie/mpt_cursor.rs#L950)):*
<details><summary><i>Previously, peilun-conflux wrote…</i></summary><blockquote>

> ```
> 
>                         child_node.mpt = self.take_mpt();
>                         self.mpt = child_node.write_out()?;
> ```
Move out of if-else/
</blockquote></details>

Done.
___
*[core/src/storage/impls/snapshot_sync/offer/mpt_slicer.rs, line 83 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveW5-eCgxiohkdtyfb:-LvebP-54KqQaQ45BRBV:b-896fix) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/snapshot_sync/offer/mpt_slicer.rs#L83)):*
<details><summary><i>Previously, peilun-conflux wrote…</i></summary><blockquote>

> ```
>                 // FIXME: try if we can do it.
> ```
remove.
</blockquote></details>

Done.

**Review by yangzhe1990 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @peilun-conflux)

___
*[core/src/storage/impls/storage_db/sqlite.rs, line 195 at r2](https://reviewable.io/reviews/peilun-conflux/conflux-rust/2#-LveXK8p7wq_GRtcNc1b:-Lvf3NOX59tFssnugNkz:b-868zjp) ([raw file](https://github.com/peilun-conflux/conflux-rust/blob/092c18936b39648dd56acd78c2dca5a7914f5927/core/src/storage/impls/storage_db/sqlite.rs#L195)):*
<details><summary><i>Previously, peilun-conflux wrote…</i></summary><blockquote>

> ```
> 
>         for path in Self::possible_temporary_files(db_path) {
>             match fs::remove_file(path) {
>                 Ok(_) => {
>                     removed = true;
>                 }
> ```
Double check.
</blockquote></details>

There is no longer wal and shm file locally on linux.

**Pull request merged**
